import { GoogleGenerativeAI } from '@google/generative-ai'
import { normalizeMaInSlug, maAdvisorDateFallbackSlug, polishAutoGeneratedSlugVariableSegment } from '@/lib/slugNormalize'
import { loadIntroHistory, saveIntroEntry, extractFirstSentence, buildUsedIntrosBlock } from '@/lib/introHistory'
import { generateWithClaude, isClaudeConfigured } from '@/lib/api/claude'

/**
 * generateContent を順に試すモデル。
 * gemini-1.5-* は 2025年9月に廃止済みのため 2.x 系のみを候補にする。
 * 404（モデル不存在）→ 次モデルへ、429/503 → 同一モデル待機再試行、最終失敗 → Claude(Bedrock)。
 * 上書き: 環境変数 GEMINI_MODEL_LIST にカンマ区切り（例: gemini-2.5-flash,gemini-2.0-flash）
 */
const DEFAULT_GEMINI_MODELS = [
  'gemini-2.5-flash',
  'gemini-2.5-flash-lite',
  'gemini-2.0-flash',
  'gemini-2.0-flash-lite',
] as const

function getGeminiModelIds(): readonly string[] {
  const raw = process.env.GEMINI_MODEL_LIST?.trim()
  if (!raw) return DEFAULT_GEMINI_MODELS
  const parsed = raw.split(',').map((s) => s.trim()).filter(Boolean)
  return parsed.length > 0 ? parsed : DEFAULT_GEMINI_MODELS
}

/** SDK / Google 側のエラーをログ・ユーザー向け詳細用に1行にまとめる */
function formatGeminiCaughtError(e: unknown): string {
  if (e instanceof Error) {
    const withCause = e as Error & { cause?: unknown }
    const tail =
      withCause.cause !== undefined && withCause.cause !== null
        ? ` | cause: ${formatGeminiCaughtError(withCause.cause)}`
        : ''
    return `${e.message}${tail}`
  }
  if (e && typeof e === 'object' && 'message' in e && typeof (e as { message: unknown }).message === 'string') {
    return (e as { message: string }).message
  }
  try {
    return JSON.stringify(e)
  } catch {
    return String(e)
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

function readPositiveIntEnv(name: string, fallback: number): number {
  const raw = process.env[name]?.trim()
  if (!raw) return fallback
  const n = parseInt(raw, 10)
  return Number.isFinite(n) && n > 0 ? n : fallback
}

/** Google 429 応答の「Please retry in 24.9s」や RetryInfo から待機秒を読む */
function parseRetryDelaySeconds(detail: string): number | null {
  const m1 = detail.match(/Please retry in ([\d.]+)\s*s/i)
  if (m1) {
    const sec = parseFloat(m1[1]!)
    if (Number.isFinite(sec) && sec >= 0) return Math.min(sec, 120)
  }
  const m2 = detail.match(/"retryDelay"\s*:\s*"(\d+)s"/i)
  if (m2) {
    const sec = parseInt(m2[1]!, 10)
    if (Number.isFinite(sec) && sec >= 0) return Math.min(sec, 120)
  }
  return null
}

/**
 * Gemini の候補モデルを順に試して generateContent を実行する。
 * - 429（quota）・503（high demand）時は短い待機で同一モデルを再試行し、
 *   それでもダメなら次モデルへフォールバック。
 * - 404（モデル不存在・generateContent 非対応）は待機せず即時次モデルへ。
 * - 全候補が失敗した場合は最後のエラー詳細を含めて throw する。
 */
async function tryGeminiModels(apiKey: string, prompt: string): Promise<string> {
  const genAI = new GoogleGenerativeAI(apiKey)
  const maxRetriesPerModel = 2
  // Vercel の関数タイムアウト(504)回避のため、Gemini 側の試行時間に上限を設ける
  const totalBudgetMs = readPositiveIntEnv('GEMINI_TOTAL_BUDGET_MS', 55_000)
  const maxRetryWaitMs = readPositiveIntEnv('GEMINI_MAX_RETRY_WAIT_MS', 8_000)
  const startedAt = Date.now()
  let lastError: Error | null = null
  let lastDetail = ''

  const modelIds = getGeminiModelIds()
  for (const modelId of modelIds) {
    for (let attempt = 0; attempt < maxRetriesPerModel; attempt++) {
      if (Date.now() - startedAt >= totalBudgetMs) {
        console.warn('[Gemini] 総予算時間を超過したため、次の経路へ切り替えます')
        break
      }
      try {
        const model = genAI.getGenerativeModel({ model: modelId })
        const result = await model.generateContent(prompt)
        return result.response.text()
      } catch (e) {
        lastError = e instanceof Error ? e : new Error(String(e))
        lastDetail = formatGeminiCaughtError(e)
        console.error(`[Gemini] model=${modelId} attempt=${attempt + 1}/${maxRetriesPerModel} 失敗:`, lastDetail)

        const combined = `${lastError.message}\n${lastDetail}`

        const isModelUnavailable =
          /404|NOT_FOUND|not found for API version|is not supported for generateContent|ListModels|is not available|deprecat/i.test(combined)
        if (isModelUnavailable) {
          console.warn(`[Gemini] model=${modelId} は利用不可のためスキップして次モデルを試します`)
          break
        }

        // 1日クォータ超過（429 Quota Exceeded）は同一モデルで待機しても無意味なため
        // 即座に次のモデルへスキップする
        const isQuotaExhausted =
          /429|quota exceeded|Too Many Requests|RESOURCE_EXHAUSTED|Quota exceeded for metric.*free_tier/i.test(combined)
        if (isQuotaExhausted) {
          console.warn(`[Gemini] model=${modelId} クォータ超過のため次のモデルへスキップします`)
          break
        }

        const isRetryable =
          /Resource exhausted|503|Service Unavailable|high demand|Overloaded/i.test(combined)

        if (!isRetryable) {
          // 非クォータ系の未分類エラーはループを抜けて次の経路へ
          break
        }

        const canRetry = attempt < maxRetriesPerModel - 1
        if (canRetry) {
          const waitSec = parseRetryDelaySeconds(lastDetail)
          const requestedMs = waitSec != null ? Math.ceil(waitSec * 1000) + 800 : 5_000
          const ms = Math.min(requestedMs, maxRetryWaitMs)
          const elapsed = Date.now() - startedAt
          const remaining = totalBudgetMs - elapsed
          if (remaining <= 1_000) {
            console.warn('[Gemini] 残り時間不足のため待機再試行をスキップし、次の経路へ進みます')
            break
          }
          const boundedMs = Math.min(ms, Math.max(0, remaining - 700))
          if (boundedMs <= 0) {
            console.warn('[Gemini] タイムバジェット上、待機再試行できないため次へ進みます')
            break
          }
          console.warn(`[Gemini] ${ms}ms 待機して再試行します (${modelId})`)
          await sleep(boundedMs)
          continue
        }
        console.warn(`[Gemini] ${modelId} で${maxRetriesPerModel}回失敗。次のモデルへフォールバック`)
        break
      }
    }
  }

  console.error('[Gemini] 全候補モデルで失敗', { models: [...modelIds], lastDetail })
  const suffix = lastDetail ? ` [Gemini詳細: ${lastDetail}]` : ''
  throw lastError ?? new Error(`Gemini 生成に失敗しました${suffix}`)
}

/** Claude（Bedrock）で生成する。未設定なら例外。 */
async function tryClaude(prompt: string): Promise<string> {
  if (!isClaudeConfigured()) {
    throw new Error('Claude（Bedrock）が未設定です（AWS 認証情報を確認してください）')
  }
  const claudeText = await generateWithClaude(prompt, {
    maxTokens: 8000,
    temperature: 0.7,
  })
  console.log(`[Claude] 生成成功（文字数: ${claudeText.length}）`)
  return claudeText
}

/**
 * 記事生成の本体。既定では Claude（Bedrock / Sonnet 4.6）を主エンジンとして使い、
 * 失敗時に Gemini へフォールバックする。
 * 環境変数 AI_PRIMARY=gemini を指定すると旧来の Gemini 優先に戻せる。
 */
async function generateContentWithFallback(apiKey: string, prompt: string): Promise<string> {
  const primary = (process.env.AI_PRIMARY?.trim().toLowerCase() || 'claude')

  if (primary === 'gemini') {
    // 旧来順序: Gemini → Claude
    try {
      return await tryGeminiModels(apiKey, prompt)
    } catch (geminiErr) {
      const geminiDetail = geminiErr instanceof Error ? geminiErr.message : String(geminiErr)
      if (!isClaudeConfigured()) {
        throw new Error(
          'Gemini API が一時的に利用できません（サーバー混雑またはクォータ超過）。' +
            `しばらく待ってから再度お試しください。 [詳細: ${geminiDetail}]`,
        )
      }
      try {
        console.warn('[Gemini→Claude] Gemini 失敗のため Claude にフォールバックします')
        return await tryClaude(prompt)
      } catch (claudeErr) {
        const claudeDetail = claudeErr instanceof Error ? claudeErr.message : String(claudeErr)
        throw new Error(`Gemini・Claude 両方の生成に失敗しました。Claude詳細: ${claudeDetail} [Gemini詳細: ${geminiDetail}]`)
      }
    }
  }

  // 既定順序: Claude（主）→ Gemini（予備）
  try {
    return await tryClaude(prompt)
  } catch (claudeErr) {
    const claudeDetail = claudeErr instanceof Error ? claudeErr.message : String(claudeErr)
    console.warn('[Claude→Gemini] Claude 失敗のため Gemini にフォールバックします:', claudeDetail)
    try {
      return await tryGeminiModels(apiKey, prompt)
    } catch (geminiErr) {
      const geminiDetail = geminiErr instanceof Error ? geminiErr.message : String(geminiErr)
      throw new Error(`Claude・Gemini 両方の生成に失敗しました。Claude詳細: ${claudeDetail} [Gemini詳細: ${geminiDetail}]`)
    }
  }
}

/**
 * 汎用テキスト生成（Claude主・Gemini予備）。
 * 記事生成以外の用途（仮説ペルソナ生成など）から利用する。
 */
export async function generateTextWithFallback(prompt: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY ?? ''
  return generateContentWithFallback(apiKey, prompt)
}

interface ParsedArticleResult {
  title: string
  content: string
}

/**
 * モデルが「出力形式」説明文を混ぜて返した場合でも、実データに近い
 * タイトル＋本文ブロックを抽出する。
 */
function parseGeneratedArticleText(text: string): ParsedArticleResult {
  const normalized = text.replace(/\r\n/g, '\n')
  const lines = normalized.split('\n')
  let best: ParsedArticleResult | null = null

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!.trim()
    const m = line.match(/^タイトル[:：]\s*(.+)\s*$/)
    if (!m) continue
    const candidateTitle = m[1]!.trim()
    if (!candidateTitle || /（記事タイトル）/.test(candidateTitle)) continue

    // --- 区切りをタイトル行から最大20行先まで探す（空白行が多くても対応）
    let sepIdx = -1
    for (let j = i + 1; j <= Math.min(i + 20, lines.length - 1); j++) {
      if (/^\s*-{3,}\s*$/.test(lines[j]!)) {
        sepIdx = j
        break
      }
    }
    if (sepIdx === -1) continue

    const candidateContent = lines.slice(sepIdx + 1).join('\n').trim().replace(/^-\s*/, '')
    if (!candidateContent) continue
    if (!best || candidateContent.length > best.content.length) {
      best = { title: candidateTitle, content: candidateContent }
    }
  }

  if (best) return best

  // フォールバック: タイトル行を正規表現で抽出、プレースホルダーは除外
  const fallbackTitleMatch = normalized.match(/タイトル[:：]\s*([^（\n][^\n]+)/)
  const rawFallbackTitle = fallbackTitleMatch?.[1]?.trim() ?? ''
  const isPlaceholder = !rawFallbackTitle || /（記事タイトル）/.test(rawFallbackTitle)
  const fallbackTitle = isPlaceholder ? '' : rawFallbackTitle

  // タイトル行の末尾位置を特定
  const titleLineEnd = fallbackTitleMatch
    ? normalized.indexOf('\n', normalized.indexOf(fallbackTitleMatch[0]))
    : -1

  if (titleLineEnd >= 0) {
    // タイトル行以降の全テキストを本文として取得する。
    // これにより「本文の途中に --- がある（FAQ前など）」ケースでも
    // FAQ のみが content になるバグを防ぐ。
    let bodyText = normalized.slice(titleLineEnd + 1).trim()
    // タイトル直後の --- は出力フォーマットの区切り文字なので除去
    bodyText = bodyText.replace(/^\s*-{3,}\s*\n?/, '')
    return { title: fallbackTitle, content: bodyText }
  }

  // titleLineEnd が取れない最終フォールバック
  const fallbackSep = normalized.indexOf('---')
  const fallbackContent = fallbackSep >= 0
    ? normalized.slice(fallbackSep + 3).trim().replace(/^-\s*/, '')
    : normalized.replace(/タイトル[:：].+/, '').trim()

  return { title: fallbackTitle, content: fallbackContent }
}

const TITLE_MARKER = '<<<TITLE>>>'
const BODY_MARKER = '<<<BODY>>>'

/**
 * マーカー方式（<<<TITLE>>> / <<<BODY>>>）でタイトル・本文を抽出する。
 * マーカーが見つからない場合は旧形式（タイトル：…\n---\n本文）のパーサーへ、
 * それも失敗した場合は「全文を本文」として返す（throwしない）。
 */
function parseArticleOutput(text: string): ParsedArticleResult {
  const normalized = text.replace(/\r\n/g, '\n')

  const titleIdx = normalized.indexOf(TITLE_MARKER)
  const bodyIdx = normalized.indexOf(BODY_MARKER)

  if (titleIdx !== -1 && bodyIdx !== -1 && bodyIdx > titleIdx) {
    const rawTitle = normalized
      .slice(titleIdx + TITLE_MARKER.length, bodyIdx)
      .trim()
      // 「タイトル：」を重ねて書いてくるケースを吸収
      .replace(/^タイトル[:：]\s*/, '')
      // タイトルが複数行になった場合は1行目のみ
      .split('\n')[0]!
      .trim()
    const rawBody = normalized.slice(bodyIdx + BODY_MARKER.length).trim()
    const title = /（記事タイトル）|（推敲後タイトル）/.test(rawTitle) ? '' : rawTitle
    if (rawBody) {
      return { title, content: rawBody }
    }
  }

  // 本文側だけマーカーがあるケース（タイトルマーカー欠落）
  if (bodyIdx !== -1) {
    const rawBody = normalized.slice(bodyIdx + BODY_MARKER.length).trim()
    const beforeBody = normalized.slice(0, bodyIdx)
    const titleMatch = beforeBody.match(/タイトル[:：]\s*([^\n]+)/)
    const title = titleMatch?.[1]?.trim() ?? ''
    if (rawBody) {
      return {
        title: /（記事タイトル）|（推敲後タイトル）/.test(title) ? '' : title,
        content: rawBody,
      }
    }
  }

  // 旧形式（タイトル：…\n---\n本文）フォールバック
  return parseGeneratedArticleText(normalized)
}

const SUPERVISOR_BLOCK = `監修者
株式会社日本提携支援 代表取締役
大野 駿介
過去1,000件超のM&A相談、50件超のアドバイザリー契約、15組超のM&A成約組数を担当。(株)日本M&Aセンターにて、年間最多アドバイザリー契約受賞経験あり。新規提携先の開拓やマネジメント経験を経て、(株)日本提携支援を設立。`

const FOOTER = `導入事例はこちらから
https://nihon-teikei.co.jp/news/casestudy/`

export interface RefinedArticle {
  refinedTitle: string
  refinedContent: string
}

export interface FirstDraftResult {
  title: string
  content: string
}

/** 一次執筆・推敲本文から監修者テキストブロックを除去する */
function stripSupervisorText(content: string): string {
  if (!content) return content
  return content
    // 「監修者：株式会社日本提携支援 代表取締役 大野 駿介」の行
    .replace(/.*監修者：株式会社日本提携支援 代表取締役 大野 駿介.*\n?/g, '')
    // 「実績：過去1,000件超のM&A相談...」の行（M&A / M&amp;A の両方）
    .replace(/.*実績：過去1,000件超のM(&amp;|&)A相談、50件超のアドバイザリー契約、15組超のM(&amp;|&)A成約組数を担当。.*\n?/g, '')
    // 「(株)日本M&Aセンターにて、年間最多アドバイザリー契約受賞経験あり。」の行（M&A / M&amp;A の両方）
    .replace(/.*\(株\)日本M(&amp;|&)Aセンターにて、年間最多アドバイザリー契約受賞経験あり。.*\n?/g, '')
    // 余分な空行を1行に圧縮
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/** PREPラベル（P/R/E/P）を本文先頭ラベルから除去する（表示崩れ防止の安全策） */
function stripPrepLabels(content: string): string {
  if (!content) return content
  return content
    .replace(
      /^\s*(?:・\s*)?(?:\*\*)?\s*[PRE]\s*[（(][^）)]+[）)]\s*[：:]\s*/gm,
      ''
    )
    .replace(
      /^\s*(?:・\s*)?(?:\*\*)?\s*P\s*[（(]\s*まとめ\s*[）)]\s*[：:]\s*/gm,
      ''
    )
}

/** 画像バナー配置のプレースホルダー指示を除去する */
function stripBannerPlaceholders(content: string): string {
  if (!content) return content
  return content.replace(/\[ここに[^\]]*画像バナーを配置\]/g, '').replace(/\n{3,}/g, '\n\n')
}

/** KW 鉤括弧を外し、小文字 m&a を M&A に正規化する */
function normalizeKeywordInText(s: string): string {
  if (!s) return s
  let out = s
  out = out.replace(/「(m&a[^」]{0,20})」/gi, '$1')
  out = out.replace(/\bm&a\b/gi, 'M&A')
  return out
}

/** Markdown 太字 **...** を除去（内側の文字列は残す）。孤立した ** も削除する */
function stripMarkdownDoubleAsterisk(s: string): string {
  if (!s) return s
  let out = s
  let prev = ''
  while (out !== prev) {
    prev = out
    out = out.replace(/\*\*([\s\S]*?)\*\*/g, '$1')
  }
  return out.replace(/\*\*/g, '')
}

/** プロンプトと参照データから一次執筆（タイトル＋本文）を生成する */
export async function generateFirstDraftFromPrompt(
  userPrompt: string,
  targetKeyword?: string,
  dataContext?: string,
  toneExamples?: string,
  avoidHeadings?: string,
  competitorContext?: string
): Promise<FirstDraftResult> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) throw new Error('GEMINI_API_KEY が設定されていません')

  const introHistory = await loadIntroHistory()
  const usedIntrosBlock = buildUsedIntrosBlock(introHistory)

  const prompt = `あなたは株式会社日本提携支援（NTS）専属の上級コンテンツストラテジストです。
以下の【参照資料】を徹底的に読み込み、NTSにしか書けない記事を執筆してください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【NTS固定情報】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・監修者・実績のテキストは本文に含めないでください。投稿時に画像ブロックで表示されます。
・末尾CTA：導入事例はこちらから https://nihon-teikei.co.jp/news/casestudy/
・「[ここに〜画像バナーを配置]」のようなプレースホルダー指示は絶対に出力しないこと。画像バナーの配置はシステム側で自動処理される。

■ 個人情報・機密情報の保護（最重要・違反厳禁）
・本文中に**実在の企業名（NTS＝株式会社日本提携支援を除く）・個人名・住所・電話番号**を絶対に出力しないこと。
・参照資料に社名・個人名が含まれていても、記事本文では「ある建設業のお客様」「製造業を営むオーナー経営者」のように業種・立場だけを残して匿名化すること。
・年商・従業員数・成約価格・期間などの数値は、参照資料に明記されている数値のみ使用可。参照資料にない数値を創作しないこと（「年商約10億円」「約XX名規模」等の架空数値は厳禁）。
・導入事例を引用する場合は「NTSが支援したあるケースでは〜」という形式にし、固有名詞・架空の数値は一切使わないこと。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【出力形式】※必ずこの形式を守ること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<<<TITLE>>>
（記事タイトル）
<<<BODY>>>
（本文）

※ <<<TITLE>>> の次の行に記事タイトルのみを1行で記述してください。
※ <<<BODY>>> の下には記事本文のみを記述してください。タイトル・監修者ブロックのテキストは含めないでください。
※ <<<TITLE>>> と <<<BODY>>> のマーカーは必ずこの表記のまま出力してください。

${toneExamples?.trim() ? `━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【文体・トーン参考（過去の近似記事）】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
以下の過去記事と同じトーン・語り口・文体・文末表現で執筆してください。
テーマ・内容・見出し構成は今回の【執筆テーマ・指示】に従い、まったく新しい記事を書くこと。
（過去記事の文章をそのままコピーしないこと。あくまで文体の参考にとどめること）

${toneExamples}

` : ''}${avoidHeadings?.trim() ? `━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【過去記事との差別化指示（最重要）】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
以下は過去に同テーマ・近いキーワードで書いた記事の見出し構成・冒頭抜粋です。
今回の記事は次のすべてを過去記事と変えること：
- 見出しタイトル（同じ見出しの使い回し禁止。類似した言い換えも禁止）
- 導入（リード文）の切り口・書き出しのアプローチ
- 主要な論点の展開順序・構成
- 使用する事例・具体例・数値の引き合いに出し方
特に【同一KWの過去記事・重複厳禁】と記載された記事とは、読者が「同じ記事の焼き直し」と感じない、
まったく別の角度（例：対象読者層を変える、フェーズを変える、失敗例起点にする等）から書くこと。

${avoidHeadings}

` : ''}${competitorContext?.trim() ? `━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【競合分析データ】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
以下のAhrefsデータを参考に、競合より具体的・詳細・NTS固有の情報量で上回る記事を書くこと。

${competitorContext}

` : ''}━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【執筆テーマ・指示】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${userPrompt}

${targetKeyword?.trim() ? `ターゲットキーワード：${targetKeyword}\n※タイトルと本文の自然な箇所に必ず盛り込むこと。` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【参照資料】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${dataContext?.trim() ? `
以下の資料を読み込んだ上で、下記の【資料活用ルール】に従って執筆すること。

${dataContext}
` : '（資料なし：プロンプトのみで執筆）'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【資料活用ルール】※資料がある場合は必ず全て実行すること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

■ 参照資料と【執筆テーマ・指示】の優先順位（最重要）
1. 【執筆テーマ・指示】およびターゲットキーワードが、記事の主題・見出し構成・論点の最優先。参照資料は補助であり、資料の目次に従って記事を書いてはならない。
2. 参照資料に「M&Aの成功率」「失敗する理由」「よくある手順」などの**定番・網羅的な解説フロー**が含まれていても、それを**記事の章立てとしてなぞらない**。今回のテーマ・KWに**直接必要な事実・数値・用語・事例だけ**を抜き出して使う。
3. テーマとズレた一般論を「資料にあるから」という理由で厚く書かない。不要なセクションは設けない。
4. 「S3資料にも記載されているように」「資料によると」「社内資料では」など、**参照資料そのものを指し示すメタな言い回しは禁止**。読者向けの自然な本文に溶け込ませる。
5. 資料の断片が毎回似ていても、**今回のプロンプトで指定した切り口・論点だけ**を深掘りし、別記事と同じ見出し並びの汎用解説にしない。

■ Ahrefsデータがある場合の使い方
1. 競合記事が上位表示されているキーワードと検索意図を把握する
2. 競合記事が薄い・触れていない論点を特定する
3. その論点をNTS記事の差別化ポイントとして見出しに使う
4. 競合より詳しく・具体的に書く（文字数・事例数・具体性で上回る）
5. 競合が使っていない切り口・角度から題材にアプローチする

■ NTS社内資料（事例・相談記録・ノウハウ等）がある場合の使い方
1. 資料中の具体的な数値・金額・期間・業種を、**今回のテーマに関係するときだけ**本文に使う（無関係な定番統計の羅列は避ける）
2. 「〜というケースがありました」という形で実際の事例を本文に組み込む（テーマと結びつく事例に限定）
3. 「NTSでは〜」「大野が現場で感じるのは〜」という一人称の知見として書く
4. 一般論を述べた後、必ずNTSの現場視点でその一般論を補強または修正する（ただし上記「参照資料の優先順位」に反しないこと）
5. 資料にある数値は出典明記不要でそのまま使用してよい

■ 両方ある場合
Ahrefsで競合の弱点を特定 → NTS社内資料でその弱点を埋める
という構造で記事全体を設計する

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【執筆の絶対ルール】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

❶ 導入（冒頭の2〜3文）の設計
■ あなたの仕事：
今回の記事テーマ・キーワード・想定読者（45〜70代の中小企業経営者）を踏まえ、
「この記事でしか使えない、この記事だからこそ意味がある一文目」を自分で考えること。
他の記事の冒頭をコピーしたような汎用的な書き出しは一切禁止。

■ 導入で禁止すること（以下に該当する書き出しは不可）：
・「近年〜」「〜が問題となっています」「〜が注目されています」などの時事導入
・「後継者が見つからないまま」「気がつけば●歳を超えていた」のような年齢+後継者不在の定型描写
・「売上は安定しているのに」「会社の将来が描けない」のような漠然とした将来不安の描写
・「ある日突然〜」「ふと気がつくと〜」のような物語調の紋切り型
・「〜という言葉を耳にする機会が増えました」のような受動的な時事導入
・前回までの記事と同じ構造・同じ語彙の導入（下記の使用禁止リスト参照）

■ 導入で意識すること：
・読者が「お、これは今まで読んだ記事と違うな」と感じる一文目にする
・テーマに固有の具体的な場面・数字・問い・事実から入る
・「悩みの共感」以外にも、反直感的な事実提示、具体的なシーン描写、
  読者への直接的な問いかけ、業界の構造的な変化の指摘、
  意外な統計データ、現場で実際に聞いた一言の引用など、自由にアプローチしてよい
・同じメディアの他記事と並んだときに「毎回違う切り口で書いている」と感じられることが最重要

${usedIntrosBlock}

❷ NTSの実績を本文の根拠として使う
「地方自治体との連携協定実績」「600件以上の相談実績」等の数値を
抽象的な説明の裏付けとして本文中で活用すること。
「NTSでは〜」という形で必ず2〜3箇所登場させること。

❸ 一般論で終わらせない
各見出しセクションで「一般的には〜」で終わる説明の後に、
必ず「NTSの現場では〜」「実際の事例では〜」という
具体・固有の情報を続けること。

❹ PREP法で各セクションを構成する
P（結論）→ R（理由）→ E（NTS事例・具体例）→ P（まとめ）
の順で書くこと。特にE（事例）を省略しないこと。
ただし本文中に「P（結論）」「R（理由）」「E（NTS事例・具体例）」「P（まとめ）」などのラベルは出力しないこと。

❺ 末尾は必ずCTAで締める
- まとめセクションの末尾には必ず以下の文章をそのまま使うこと（一字一句変更しないこと）：
「NTSは、M&Aを真の「提携支援」と位置付け、地方自治体との連携協定実績や600件以上の相談実績を通じて培ってきたノウハウで、中小企業の経営者の皆様のM&Aを力強くサポートいたします。M&Aについてご不明な点や不安なことがあれば、どんな些細なことでも構いません。ぜひ一度、NTSにご相談ください。」
- その後に「導入事例はこちらから https://nihon-teikei.co.jp/news/casestudy/」を必ず含めること。
- さらにその下に「新しいM&A ニュースタンダードはこちら https://nihon-teikei.co.jp/ma-newstandard/」を必ず含めること。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【構成・文体ルール】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- 本文は2500文字以上（資料が豊富な場合は3000文字以上を目指す）
- 見出しは「1. 」「2. 」番号付き形式、小見出しは「1-1.」形式
- 【重要】見出し・小見出しの直後には必ず100文字以上の本文段落を1つ以上書くこと。見出しの次の行が別の見出し・小見出しになることは絶対禁止。例：「1. ○○」の直後に「1-1. △△」が来ることも禁止。必ず「1. ○○」→本文→「1-1. △△」の順にすること。
- 専門用語には初出時に括弧で解説（例：デューデリジェンス（DD：企業調査））
- マークダウン記法（##・**・__ 等）は一切使用しない。強調したい語は鉤括弧「 」で囲むか、句点で文を区切って表現すること
- 本文中でセクション区切りとして「---」（水平線）を一切使用しないこと。セクションの切り替えは番号付き見出しで表現すること
- 段落や箇条書き項目の冒頭を **ラベル：内容** のように太字で囲まない。ラベル付けしたい場合は「1-1. ラベル」の見出し形式か、「ラベル：内容」のようにプレーンテキストで書くこと
- 手順や項目を列挙するときは、必ず「1. 見出し」「1-1. 小見出し」の番号形式を使うこと。行全体を「**」で囲んだ太字行を連続で並べないこと
- 箇条書きは多用しない。文章で表現できるものは文章にする
- 文末表現のバリエーションを意識する（〜です・〜ますの繰り返しを避ける）
- 対象読者：45〜70代の中小企業経営者（難解な金融用語は必ず解説付き）

■ トーン・人称ルール（厳守）
- NTSや日本提携支援に言及するときは「私たちは〜」「弊社では〜」「NTSでは〜」と自社視点で書くこと。「NTSは確信している」「NTSは考える」のように三人称で客体化しない。
- 文末は「〜です」「〜ます」「〜ています」「〜と考えています」のように丁寧語で統一する。「〜だろう」「〜であろう」「〜に他ならない」「〜と言えよう」のような評論家・学術論文調は禁止。
- 「徹底解説する」「完全ガイド」「網羅する」のようなYouTubeサムネイル的な煽り表現は使わない。
- 「〜に尽きるだろう」「〜が肝要だ」「〜せねばならない」のような硬い書き言葉は避け、経営者に語りかける実務的なトーンにする。

■ ターゲットキーワードの表記ルール（厳守）
- ターゲットキーワードは本文中に自然に溶け込ませること。「」（鉤括弧）で囲んだまま繰り返さない。
- キーワードがアルファベットの場合は正式な大文字表記にする（例：m&a → M&A、pmi → PMI）。
- 「m&a 相談」のような半角小文字＋スペース入りのまま本文に書かない。「M&Aの相談」「M&Aについて相談する」のように自然な日本語にする。

- 記事の末尾に番号付き見出し形式（例：「5. よくある質問（FAQ）」）でFAQセクションを含めること。このセクション前に「---」を置かないこと。Q. と A. の形式で5つ程度の質問と回答を作成し、質問はターゲットキーワードに関連するユーザーの疑問を反映したものにすること。

❻ 架空の数値・事例の作り込み禁止（厳守）
参照資料に存在しない数値（年商・従業員数・成約金額・所要期間等）を文章の説得力のために創作しないこと。
事例を紹介するときは「NTSが支援したあるケースでは〜」という形にとどめ、その中に架空の数値・具体的な規模感を入れないこと。
参照資料に明記された数値以外は「ある中小企業」「ある製造業の経営者」程度の粒度にする。`.trim()

  const raw = await generateContentWithFallback(apiKey, prompt)

  // マークダウンの **太字**・*斜体*・# 見出しはすべて除去（推敲側と挙動を揃える）
  let text = stripMarkdownDoubleAsterisk(raw)
  text = text
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/\*/g, '')
    .replace(/^#{1,6}\s+/gm, '')

  const parsed = parseArticleOutput(text)
  const title = parsed.title
  let content = parsed.content

  // 本文の先頭にタイトルが残っていれば削除
  content = content.replace(/^タイトル[:：][^\n]+\n+/, '').trim()
  if (title !== '（タイトルなし）' && content.startsWith(title)) {
    content = content.substring(title.length).trim()
  }
  content = stripPrepLabels(content)
  content = stripBannerPlaceholders(content)
  content = normalizeKeywordInText(content)

  try {
    const firstSentence = extractFirstSentence(content)
    if (firstSentence) {
      await saveIntroEntry(targetKeyword ?? '', firstSentence)
    }
  } catch (e) {
    console.warn('[IntroHistory] 保存失敗（記事生成には影響なし）:', e)
  }

  return {
    title: title || '（タイトルなし）',
    content: content || '',
  }
}

export async function refineArticleWithGemini(
  title: string,
  content: string,
  targetKeyword?: string,
  referenceMaterialsContext?: string
): Promise<RefinedArticle> {
  // 元記事から監修者テキストを事前に除去
  const cleanedContent = stripSupervisorText(content)

  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) throw new Error('GEMINI_API_KEY が設定されていません')

  const materialsBlock =
    referenceMaterialsContext?.trim().length ?
      `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【推敲用・参照資料（一次執筆時と同一ウィンドウ）】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
以下は一次執筆時にモデルへ渡した資料連結テキストから、同一の文字範囲を再現したものです。

${referenceMaterialsContext.trim()}

■ 推敲時の参照の扱い（厳守）
1. 【元記事】の構成・論旨・ユーザーが意図的に削った表現を最優先。資料の内容で上書き・矮小化してはならない。
2. 資料から補強・追記するのは、【元記事】とターゲットキーワードに直接関係し、かつNTSの現場知・数値・事例として自然に溶け込む場合に限る。
3. 「資料によると」「社内資料」「S3」「参照資料」など資料を指すメタ表現は禁止（【D2】と同様）。
4. 資料と【元記事】が矛盾する場合は【元記事】を正とし、当該資料の取り込みは見送る。
5. 参照資料に含まれる企業名・個人名等は本文では匿名化する（【D3】と同様）。

`
      : ''

  const prompt = `あなたは株式会社日本提携支援（NTS）の編集長です。
以下の記事を精査・推敲してください。

この記事は専門メディア「M&Aアドバイザーへの相談・契約」の公式コラム最終稿として仕上げること。
一次情報の現場感・根拠ある主張・50〜70代経営者向けの実務寄りが伝わる「二次執筆」にすること（一般論の羅列や教科書調の説明で終わらせない）。
Markdownの**太字**・**で囲むラベル**は禁止。段落内の小見出しが必要な場合のみ「◯◯：」の1行形式にすること。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【NTS固定情報：推敲後も必ず維持すること】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・監修者・実績のテキストは本文に含めないでください。投稿時に画像ブロックで表示されます。
・末尾CTA：導入事例はこちらから https://nihon-teikei.co.jp/news/casestudy/
  新しいM&A ニュースタンダードはこちら https://nihon-teikei.co.jp/ma-newstandard/

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【元記事】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
タイトル：${title}

本文：
${cleanedContent}

${targetKeyword?.trim() ? `ターゲットキーワード：${targetKeyword}` : ''}
${materialsBlock}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【推敲チェックリスト：上から順に確認・修正すること】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

【A. タイトル】
□ ターゲットキーワードが自然に含まれているか
□ 数字・具体性が入っているか（「5つの」「失敗しない」等）
□ 32文字以内か
□ クリックしたくなる表現になっているか

【B. 冒頭】
□ 以下の定型フレーズで始まっていないか確認する：
  ・「近年〜」「〜が問題となっています」「〜が注目されています」
  ・「後継者が見つからないまま」「気がつけば●歳を超えていた」
  ・「売上は安定しているのに」「会社の将来が描けない」
  ・「ある日突然〜」「ふと気がつくと〜」
  ・「〜という言葉を耳にする機会が増えました」
  → 該当していたら、この記事のテーマに固有の具体的な場面・事実・問いから始まる導入に書き直す
□ 50〜70代経営者が「これは今まで読んだ記事と違う切り口だ」と感じる導入になっているか
  → 汎用的な悩み描写の繰り返しになっていたら、テーマ固有の具体性を入れて書き直す

【C. NTSの独自性】
□ 「NTSでは〜」「NTSの現場では〜」という固有の視点・具体の進め方が2〜3箇所以上あるか
  → なければ、本文の論点に沿って自然に追加する（押し付けにならないトーンで）
□ NTSの実績数値（1,000件・50件・15組）が本文中で使われているか
  → なければ適切な箇所に挿入する
□ 一般論だけで終わっているセクションがないか
  → あれば「NTSの現場では〜」で補強する
□ 読者が「他記事と同じ結論」で終わる印象を受けないか。タイトルが約束した論点に対するNTSならではの切り口で締める

【D. 構成・文体】
□ 冗長な表現・繰り返しを削除する
□ 文末表現のバリエーションを増やす（〜です・〜ますの連続を避ける）
□ 専門用語の解説が抜けていれば追加する
□ 見出し・小見出しの直後に本文が1行もなく別の見出しが続いている箇所がないか → あれば必ず見出しと次の見出しの間に100文字以上の説明文を補完すること。見出し→見出しの連続は完全禁止。
□ アスタリスク（*）および二重アスタリスク（**）は一切使用禁止。Markdownの太字・斜体は使わない。箇条書きは必ず「・」を使うこと（出力に * が1つも含まれないようにすること）
□ 段落や項目の冒頭を **ラベル：内容** のように太字で囲んだ行を出力しないこと。ラベル付けが必要な場合は「1-1. ラベル」の小見出しに昇格させるか、「ラベル：内容」のプレーンテキストに書き直すこと
□ 手順や項目を列挙するとき、行全体を「**」で囲んだ太字行を連続で並べないこと。必ず「1. 」「1-1. 」の番号付き見出しに直すか、段落文として自然に展開すること
□ PREPで整理する際も「P（結論）」「R（理由）」「E（事例）」「P（まとめ）」などのラベル文字は本文に出力しないこと
□ 「[ここに〜画像バナーを配置]」のようなプレースホルダー指示は絶対に出力しないこと。画像バナーの配置はシステム側で自動処理されるため、本文に含めてはならない。

【D-tone. トーン・人称・KW表記の最終チェック】
□ NTSや日本提携支援を三人称で客体化していないか（「NTSは確信している」「NTSは考える」→ NG）
  → 「私たちは〜」「弊社では〜」「NTSでは〜と考えています」に書き直す
□ 「〜だろう」「〜であろう」「〜に他ならない」「〜と言えよう」「〜が肝要だ」のような評論家・学術論文調が残っていないか
  → 「〜です」「〜と考えています」「〜が重要です」のように丁寧語に書き直す
□ 「徹底解説する」「完全ガイド」「網羅する」のような煽り表現がないか → 削除または穏やかな表現に変更
□ ターゲットキーワードが「」（鉤括弧）で囲まれたまま繰り返し使われていないか → 鉤括弧を外し自然な日本語に溶け込ませる
□ ターゲットキーワードが半角小文字のまま本文に出ていないか（例：m&a 相談 → M&Aの相談）→ 正式な大文字表記かつ自然な助詞付きに修正

【D2. テーマ一貫性（定番解説への収束を防ぐ）】
□ 「S3資料」「資料に」「社内資料に」「参照資料に」など、**資料を直接指すメタ表現**があれば削除し、読者向けの自然な表現に直す
□ タイトル・ターゲットキーワードと弱く結びついたまま、**M&Aの汎用教科書型**（例：成功率の一般論→失敗理由の列挙→定番のまとめだけ）に偏っていないか。偏っている場合は、**タイトルとKWが約束した論点**に沿って見出しと本文を組み替え、無関係な網羅セクションは削る・圧縮する（末尾の固定CTA・実績の扱いなど既存ルールは維持）

【D3. 個人情報・機密情報の保護（違反厳禁）】
□ 本文に実在の企業名（NTS＝株式会社日本提携支援を除く）が含まれていないか → あれば「A社（業種・規模）」等に匿名化する
□ 個人名・住所・電話番号が含まれていないか → あれば削除する
□ 導入事例の引用が「NTSが支援したあるケースでは〜」のように匿名化されているか
□ 参照資料に記載がない架空の数値（年商・従業員数・成約金額等）が含まれていないか → あれば「ある中小企業のケース」等の表現に置き換えて数値は削除する

【E. 末尾CTA】
□ NTSへの相談を促す自然な文章があるか
□ 「導入事例はこちらから https://nihon-teikei.co.jp/news/casestudy/」で締めているか
  → なければ追加する
□ その下に「新しいM&A ニュースタンダードはこちら https://nihon-teikei.co.jp/ma-newstandard/」を追加しているか
  → なければ追加する

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【出力形式】※必ずこの形式を守ること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<<<TITLE>>>
（推敲後タイトル）
<<<BODY>>>
（推敲後本文）

※ <<<TITLE>>> の次の行に推敲後タイトルのみを1行で記述してください。
※ <<<BODY>>> の下には推敲後本文のみを記述してください。タイトル・監修者ブロックのテキストは含めないでください。
※ <<<TITLE>>> と <<<BODY>>> のマーカーは必ずこの表記のまま出力してください。
※本文に ** や * を含めないこと（上記ルールの再確認）`.trim()

  let text = await generateContentWithFallback(apiKey, prompt)
  text = stripMarkdownDoubleAsterisk(text)
  // 斜体(*単一*)と箇条書きの * を除去・変換
  text = text
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/^\s*\*\s+/gm, '・ ')
    .replace(/\*\s+/g, '・ ')
    .replace(/\*/g, '')
    .replace(/^#{1,6}\s+/gm, '')

  // マーカー方式で抽出。形式が崩れていても throw せず、
  // タイトルは元タイトル維持・本文は全文採用でグレースフルに処理する
  const parsed = parseArticleOutput(text)
  const refinedTitle = parsed.title || title
  let refinedContent = parsed.content || text.trim()

  // 本文の先頭にタイトルが残っていれば削除
  refinedContent = refinedContent.replace(/^タイトル[:：][^\n]+\n+/, '').trim()
  if (refinedTitle && refinedContent.startsWith(refinedTitle)) {
    refinedContent = refinedContent.substring(refinedTitle.length).trim()
  }

  // 念のため推敲後本文からも監修者テキストを除去
  refinedContent = stripSupervisorText(refinedContent)
  refinedContent = stripMarkdownDoubleAsterisk(refinedContent)
  refinedContent = stripPrepLabels(refinedContent)
  refinedContent = stripBannerPlaceholders(refinedContent)
  refinedContent = normalizeKeywordInText(refinedContent)

  return {
    refinedTitle: refinedTitle || title,
    refinedContent: refinedContent || content,
  }
}

const SLUG_PREFIX = 'ma-advisor-'

function sanitizeSlugSegment(raw: string): string {
  return normalizeMaInSlug(
    raw
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60)
  )
}

/** 記事タイトル・本文・キーワードから SEO 向け英語スラッグを生成する（先頭は常に ma-advisor- 固定、続きは本文内容に即した固有部分） */
export async function generateSlugFromGemini(
  title: string,
  targetKeyword?: string,
  articleBody?: string
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey?.trim()) return fallbackSlug()

  const kwPart = targetKeyword?.trim() ? `\nTarget keyword: ${targetKeyword.trim()}` : ''
  const bodyExcerpt = (articleBody ?? '').trim().slice(0, 2000)
  const bodyPart = bodyExcerpt
    ? `\nArticle body (Japanese excerpt — use this to capture the specific topic and wording):\n${bodyExcerpt}`
    : ''

  const prompt = `You are an SEO specialist. The URL slug MUST start with the fixed prefix "ma-advisor-" followed by a UNIQUE English segment for this article.

You will output ONLY the variable segment: the part that comes AFTER "ma-advisor-". Do NOT include "ma-advisor" or "ma-advisor-" in your output.

CRITICAL: Respond in English only. NEVER use Japanese characters. Output ONLY that segment, nothing else.

RULES for the variable segment (after the fixed prefix):
- Use ONLY lowercase English letters (a-z), numbers (0-9), and hyphens (-)
- 3 to 5 words separated by hyphens
- Reflect the SPECIFIC topic using BOTH the title AND the article body excerpt below (body is primary for uniqueness)
- Do NOT use Japanese, Chinese, or any non-ASCII characters
- NEVER use the standalone token "sme" — spell it out as "small-business" (readers may not know SME)
- Do NOT output a standalone "ma" token in the variable segment. The fixed prefix "ma-advisor-" already implies M&A context; use concrete topic terms (e.g. due-diligence, succession, valuation, deal) instead of repeating "ma"
- Prefer full words such as "due-diligence" over bare "dd" when valid within the word budget
- NEVER output "m-a" as tokens; if you need M&A as words, use "mergers-acquisitions" only when essential (still avoid redundant "ma" as a lone token)

EXAMPLES (output = variable segment only):
- Title/body about choosing M&A advisors → selection-guide
- Title/body about business succession basics → business-succession-basics
- Title/body about due diligence steps → due-diligence-process-guide
- Title/body about M&A taxes, net proceeds, or tax types/calculation → selection-tax-guide
- Title/body about SME / small business M&A → small-business-due-diligence-trouble-guide (NOT sme-ma-...)

Title: ${title.trim()}${kwPart}${bodyPart}

Variable segment after "ma-advisor-":`

  try {
    const raw = await generateContentWithFallback(apiKey, prompt)
    let segment = sanitizeSlugSegment(raw)
    if (segment.startsWith('ma-advisor-')) {
      segment = segment.slice('ma-advisor-'.length).replace(/^-+/, '')
    }
    segment = segment.replace(/^ma-advisor-?/, '').replace(/^-+/, '')
    segment = polishAutoGeneratedSlugVariableSegment(segment)
    const full = segment.length >= 3 ? `${SLUG_PREFIX}${segment}` : fallbackSlug()
    return normalizeMaInSlug(full)
  } catch (e) {
    console.warn('Gemini slug generation failed:', (e as Error)?.message)
    return fallbackSlug()
  }
}

function fallbackSlug(): string {
  return maAdvisorDateFallbackSlug()
}

/** 記事タイトル・本文から画像生成用の英文プロンプトを1文で生成する（Stable Diffusion用） */
export async function generateImagePromptFromArticle(
  title: string,
  content: string
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey?.trim()) throw new Error('GEMINI_API_KEY が設定されていません')

  const contentSnippet = content.trim().slice(0, 1800)
  const prompt = `You are an expert at writing image generation prompts for professional Japanese business article thumbnails. Style: Adobe Stock–like corporate / M&A imagery — clean, trustworthy, varied compositions.

Given the TITLE and CONTENT (Japanese) below, output exactly ONE English sentence for a photorealistic 16:9 horizontal stock photo.

STEP 1 — Pick EXACTLY ONE archetype at random (use genuine randomness; do not default to the first). Match the article mood when obvious, but still vary across requests.

ARCHETYPES:
1) Overhead flat-lay: white desk, business documents, laptop with abstract colorful charts only (no legible text), pen, coffee cup, optional two plain solid wooden cubes with NO letters or carving, no people.
2) Overhead flat-lay: merger-related papers, corporate stamp, pen, reading glasses, minimal desk, no people.
3) Overhead: financial printouts and abstract bar charts, calculator, pen, clean white table, no people, no readable numbers on paper.
4) White desk workspace: open laptop with abstract dashboard graphics, scattered documents, shallow depth of field, no people.
5) Two professionals in suits at bright white desk, open binder with charts, tablet, hands reviewing materials in focus, faces soft blur or cropped out of frame, no camera-facing portrait.
6) Side angle business meeting: colleagues over documents and tablet, emphasis on desk surface and charts, faces not dominant, bright modern office.
7) Dramatic low-angle worm-eye view of glass skyscrapers converging upward, cool blue-grey steel and glass, some warm window lights, financial district, no street people.
8) Modern collaboration: light wooden desk, hands gesturing mid-conversation, laptop with abstract UI blocks, notebook and phone, strong bokeh background, casual business attire, second person blurred.
9) Conference table wide shot: team from behind or silhouettes, laptops and papers, integration or strategy feel, no clear facial close-ups.
10) Succession or legacy mood: wooden desk, leather notebook, pen, family-business documents flat-lay, warm light, no people.
11) Contract / legal mood: neat stack of agreements, fountain pen, white surface, no people, no readable clauses.
12) Default corporate: clean Japanese office desk with documents and laptop, abstract screen graphics, navy white grey palette, no people.
13) Handshake close-up: two suited professionals shaking hands across a glass desk, only forearms and cuffs visible, bright modern office, no faces, decisive corporate moment.
14) Professional bookshelf: neatly arranged law and business volumes, warm library light, blurred leather chair foreground, no people, expertise and trust atmosphere.
15) Twilight financial district: aerial wide shot of Japanese city towers with warm window glow against deep blue sky, no people, cinematic corporate ambiance.
16) Abstract data visualization: floating 3D bar charts and trend lines in clean white space, soft studio shadows, no legible labels, professional infographic concept.
17) Minimalist reception interior: low green accent plants, white walls, light oak desk, diffused daylight, no people, premium corporate interior photography.
18) Over-the-shoulder analyst: professional reviewing abstract growth chart on large monitor, second colleague blurred in background, no legible screen text, modern open-plan office.
19) Zen meeting room: natural stone accent wall, bamboo element, solid wood table, soft diffused light, no people, premium Japanese boardroom atmosphere.
20) Close-up leather notebook: open leather-bound notebook, fountain pen resting on blank page, soft bokeh of documents in background, warm premium light, no people.

GLOBAL RULES (mandatory):
- Never ask for letters, numbers, logos, watermarks, subtitles, or readable text. Charts and screens must be abstract / illegible only.
- Never describe letter blocks, engraved M or A, ampersand on cubes, or spelling words with blocks. Plain unmarked wooden cubes only if any cubes appear.
- People allowed ONLY in archetypes 5–6, 8–9, 13, 18. Then: no selfie, no glamor portrait; hands and materials in focus; faces partial or softly blurred.
- Photorealistic, professional lighting, navy/grey/white friendly palette unless archetype calls for warm or twilight tones.
- Pick archetypes 13–20 at least 40% of the time to ensure variety and avoid repetition.

OUTPUT: One English sentence only, max 50 words, no quotation marks, no explanation.

TITLE:
${title.trim()}

CONTENT (excerpt):
${contentSnippet}

Your single English sentence:`

  const raw = await generateContentWithFallback(apiKey, prompt)
  const sentence = raw.trim().replace(/^["']|["']$/g, '').trim()
  return (
    sentence ||
    'overhead flat-lay of business documents and laptop with abstract charts on white desk, plain unmarked wooden cubes optional, photorealistic corporate stock photo, 16:9'
  )
}
